# Use the latest 2.1 version of CircleCI pipeline process engine. See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1
jobs:
  build:
    docker:
      - image: jvtcl/cotracker:latest
    steps:
      - checkout
      - run:
          name: config
          command: |
            git config --global user.email "joseph.tuccillo@colorado.edu"
            git config --global user.name "jvtcl"
      - run:
          name: Push updates
          command: |
            git status
            git add --all
            git commit -m 'test update'
            git status
            git push https://${JOE_GITHUB_TOKEN}@github.com/jvtcl/covid19-co.git
            
workflows:
  version: 2.1
  daily:
    triggers:
      - schedule:
          cron: "10 22 * * *"
          filters:
            branches:
              only:
                - master
                - circleci-project-setup
    jobs:
      - build